EXPERIMENT:
  NAME: ""
  TAG: "luminet,wrn_40_2,wrn_40_1"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "LUMINET"
  TEACHER: "wrn_40_2"
  STUDENT: "wrn_40_1"
SOLVER:
  ALPHA: 75.00
  T: 8.0
  CE_WEIGHT: 1.00
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
